name: tribeseed
description: A social tribing app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_riverpod: ^0.12.1
  lint: ^1.3.0
  mockito: ^4.1.3
  regexpattern: ^1.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.1

flutter:
  uses-material-design: true
